name: gamejamsubmission
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.11.0
  background_patterns: ^0.0.9
  riverpod: ^2.3.1
  flutter_riverpod: ^2.3.1    
  flame_riverpod: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/main/    
